/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/reference`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/neighbors`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/odd-one-out`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/random`; params?: Router.UnknownInputParams; } | { pathname: `/speed/rapid`; params?: Router.UnknownInputParams; } | { pathname: `/speed/sprint`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/reference`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz/neighbors`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz/odd-one-out`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz/random`; params?: Router.UnknownOutputParams; } | { pathname: `/speed/rapid`; params?: Router.UnknownOutputParams; } | { pathname: `/speed/sprint`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/reference${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/quiz/neighbors${`?${string}` | `#${string}` | ''}` | `/quiz/odd-one-out${`?${string}` | `#${string}` | ''}` | `/quiz/random${`?${string}` | `#${string}` | ''}` | `/speed/rapid${`?${string}` | `#${string}` | ''}` | `/speed/sprint${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/reference`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/neighbors`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/odd-one-out`; params?: Router.UnknownInputParams; } | { pathname: `/quiz/random`; params?: Router.UnknownInputParams; } | { pathname: `/speed/rapid`; params?: Router.UnknownInputParams; } | { pathname: `/speed/sprint`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
